from .base import *

DEBUG = False

ALLOWED_HOSTS = ['.vercel.app']

SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURE_SSL_REDIRECT = True

# SESSION_COOKIE_SECURE = True

# CSRF_COOKIE_SECURE = True

SECURE_HSTS_PRELOAD = True