# Generated by Django 4.2.3 on 2023-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('clockAddress_1', models.CharField(max_length=100)),
                ('clockAddress_1_TimeZoneAbbre', models.CharField(max_length=10)),
                ('clockAddress_1_DST', models.BooleanField()),
                ('clockAddress_2', models.CharField(max_length=100)),
                ('clockAddress_2_TimeZoneAbbre', models.CharField(max_length=10)),
                ('clockAddress_2_DST', models.BooleanField()),
            ],
        ),
    ]
