# Generated by Django 4.2.3 on 2023-08-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='clockAddress_1_TimeZoneAbbre',
        ),
        migrations.RemoveField(
            model_name='record',
            name='clockAddress_2_TimeZoneAbbre',
        ),
        migrations.AddField(
            model_name='record',
            name='clockAddress_1_Abbreviation',
            field=models.CharField(default='EDT', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='clockAddress_1_TimeZone',
            field=models.CharField(default='America/Toronto', max_length=30),
        ),
        migrations.AddField(
            model_name='record',
            name='clockAddress_1_UTC_Offset',
            field=models.CharField(default='-04:00', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='clockAddress_2_Abbreviation',
            field=models.CharField(default='HKT', max_length=10),
        ),
        migrations.AddField(
            model_name='record',
            name='clockAddress_2_TimeZone',
            field=models.CharField(default='Asia/Hong_Kong', max_length=30),
        ),
        migrations.AddField(
            model_name='record',
            name='clockAddress_2_UTC_Offset',
            field=models.CharField(default='+08:00', max_length=10),
        ),
    ]
