# Generated by Django 4.2.6 on 2023-10-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='time_zone',
            field=models.CharField(max_length=100),
        ),
    ]
