# Generated by Django 4.2.3 on 2023-08-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_record_clockaddress_1_timezoneabbre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='clockAddress_1_Abbreviation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='clockAddress_1_TimeZone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='record',
            name='clockAddress_1_UTC_Offset',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='clockAddress_2_Abbreviation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='clockAddress_2_TimeZone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='record',
            name='clockAddress_2_UTC_Offset',
            field=models.CharField(max_length=10),
        ),
    ]
