# Generated by Django 4.2.3 on 2023-08-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_clockaddress_1_abbreviation_and_more'),
    ]

    operations = [
        migrations.RenameModel('Record', 'UserClocks')
    ]
