# Generated by Django 4.2.3 on 2023-08-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20230823_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userclocks',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
