# Generated by Django 4.2.3 on 2023-08-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_timezones_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclocks',
            name='userClocks',
            field=models.JSONField(default=['America/Toronto', 'Asia/Hong_Kong']),
            preserve_default=False,
        ),
    ]
