# Generated by Django 4.2.3 on 2023-09-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_dog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
