# Generated by Django 4.2.3 on 2023-09-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_delete_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclocks',
            name='clockAddress_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userclocks',
            name='clockAddress_1_Abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userclocks',
            name='clockAddress_1_TimeZone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userclocks',
            name='clockAddress_1_UTC_Offset',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userclocks',
            name='clockAddress_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userclocks',
            name='clockAddress_2_Abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userclocks',
            name='clockAddress_2_TimeZone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userclocks',
            name='clockAddress_2_UTC_Offset',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
