# Generated by Django 4.2.3 on 2023-09-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_userclocks_clockaddress_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclocks',
            old_name='userClocks',
            new_name='clocks',
        ),
        migrations.RemoveField(
            model_name='userclocks',
            name='clockAddress_1_DST',
        ),
        migrations.RemoveField(
            model_name='userclocks',
            name='clockAddress_2_DST',
        ),
    ]
