# Generated by Django 4.2.3 on 2023-09-21 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_rename_userclocks_userclocks_clocks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timezones',
            old_name='timezone',
            new_name='timeZone',
        ),
    ]
