# Generated by Django 4.2.6 on 2023-10-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('time_zone', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=50)),
                ('utc_offset', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('clocks', models.JSONField()),
                ('clockAddress_1', models.CharField(max_length=100, null=True)),
                ('clockAddress_1_Abbreviation', models.CharField(max_length=10, null=True)),
                ('clockAddress_1_TimeZone', models.CharField(max_length=30, null=True)),
                ('clockAddress_1_UTC_Offset', models.CharField(max_length=10, null=True)),
                ('clockAddress_2', models.CharField(max_length=100, null=True)),
                ('clockAddress_2_Abbreviation', models.CharField(max_length=10, null=True)),
                ('clockAddress_2_TimeZone', models.CharField(max_length=30, null=True)),
                ('clockAddress_2_UTC_Offset', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
